### ISSUE TITLE
Enable Dependabot 

### ISSUE THREAD

**Issue by Behemyth** [sibyl-dev/pyreal#135]
Dependabot is built into GitHub and can automatically create PRs when a pip/poetry dependency has a new version. Having individual PRs for dependencies can help maintain the test suite's functionality during the version transition. This enhancement is an alternative to manually processing the chore of checking for updates.

- To enable dependabot, add a `root/.github/dependebot.yaml` configuration file as described [here](https://github.blog/2020-06-01-keep-all-your-packages-up-to-date-with-dependabot/#keep-all-your-dependencies-updated). 

- The configuration file will look something like [this](https://docs.github.com/en/code-security/supply-chain-security/keeping-your-dependencies-updated-automatically/enabling-and-disabling-dependabot-version-updates#example-dependabotyml-file).

- To see all the available options, including the `poetry` options, visit the [configuration specification](https://docs.github.com/en/code-security/supply-chain-security/keeping-your-dependencies-updated-automatically/configuration-options-for-dependency-updates).

**Comment by Behemyth** [comment]
Note: Automatic security updates are defaulted on for each repository, This issue is to enable non-security updates.

**Comment by zyteka** [comment]
Closed by #224
