### ISSUE TITLE
Make plots dark mode compatible

### ISSUE THREAD

**Issue by zyteka** [sibyl-dev/pyreal#174]
The outputs of plot_top_contributors is currently not compatible in dark-mode, or when displayed on black backgrounds. The labels are not visible.

This can be easily fixed by putting the plot on a white background.

**Comment by wei-enwang** [comment]
<img width="622" alt="Screen Shot 2022-03-09 at 11 23 46 AM" src="https://user-images.githubusercontent.com/22818610/157485616-b0ea1ebb-8373-4336-9925-88752f9417f6.png">

**Comment by wei-enwang** [comment]
I can take this task as I have dealt with this issue with the DTE visualization module.
